First Changes
jonathanmunamire/Polyglot pull request #1
Opened 2022-10-19 11:34 UTC by jonathanmunamire

This is my first pull request on this project

2022-10-19 16:49 UTC, OLIPLICHE requested changes
Hi @jonathanmunamire, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Deploy the web pages in GitHub👏 👏
- Linter is green (the last commit have a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- Github flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## Required Changes ♻️
- Please provide a better online link of the uploaded video. The link which you shared cannot play.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- Please I provided the Link to the 👉 [Original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 16:49 UTC, OLIPLICHE commented on about.html
> +<body>
# Please **Mobile size** has a white background and same color. 
- See your design: pay attention to the color
- 
![Capture](https://user-images.githubusercontent.com/63972670/196747491-c07ec447-c499-4514-b2b4-b8300e19208b.JPG)
- See original design:
- 
![Capture](https://user-images.githubusercontent.com/63972670/196747750-9abae180-0581-4db4-90ee-4f27f34275fa.JPG)

2022-10-19 16:49 UTC, OLIPLICHE commented on index.html
> +<body>
# Desktop Size
- **Home Page**: It has a white background and same color.
- See your design
- 
![Capture](https://user-images.githubusercontent.com/63972670/196749075-c40c035e-769d-4f90-a03f-cf719787531a.JPG)
- See the original design
- 
![Capture](https://user-images.githubusercontent.com/63972670/196749399-e09b37d5-84bb-4614-9c39-8ea0f9989a54.JPG)
- **About page** is a dark background. 
- See original design:
- 
![Capture](https://user-images.githubusercontent.com/63972670/196750723-ce900872-5336-4e47-a91f-97d59196150c.JPG)

2022-10-19 16:49 UTC, OLIPLICHE commented on about.html
> +            </section>
- Please **About page** does not contain the partners' section, Kindly remove it. This applies to About page Mobile size as well
- See the original design
- 
![Capture](https://user-images.githubusercontent.com/63972670/196752621-8295832e-b535-456f-9eb2-3836631e51c8.JPG)

2022-10-19 20:02 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @jonathanmunamire 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - README file is descriptive 👏
 - Commit messages are meaningful 👏 👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 20:02 UTC, leonardodiasb commented on index.html
> +                <h2 class="greet2">POLYGLOT LANGUAGES SCHOOL <br>We're here for you! <br>2022</h2>
- [OPTIONAL] There should be at least 1, but no more than 1, `h1` tag on each page for the main title and this looks like the main title of this page. Would be nice if you change that tag for semantic purposes and better SEO.

2022-10-19 20:02 UTC, leonardodiasb commented on about.html
> +                <h2 class="greet2">POLYGLOT LANGUAGES SCHOOL <br>KIGALI (RWANDA)</h2>
- [OPTIONAL] There should be at least 1, but no more than 1, `h1` tag on each page for the main title and this looks like the main title of this page. Would be nice if you change that tag for semantic purposes and better SEO.

2022-10-19 20:02 UTC, leonardodiasb commented on about.html
> +            <a class="logo" href="index.html"><img src="IMG/logo.jpg" height="50vh"></a>
- [OPTIONAL] Please make sure the page is accessible, images should contain `alt` attributes for accessibility purposes.

2022-10-19 20:02 UTC, leonardodiasb commented on about.html
> +            <img src="IMG/logo.jpg">
- [OPTIONAL] Please make sure the page is accessible, images should contain `alt` attributes for accessibility purposes.

2022-10-19 20:02 UTC, leonardodiasb commented on index.html
> +            <a class="logo" href="index.html"><img src="IMG/logo.jpg" height="50vh"></a>
- [OPTIONAL] Please make sure the page is accessible, images should contain `alt` attributes for accessibility purposes.

2022-10-19 20:02 UTC, leonardodiasb commented on script.js
> +  <img src="${cards.teacherImage}">
- [OPTIONAL] Please make sure the page is accessible, images should contain `alt` attributes for accessibility purposes.

2022-10-19 20:02 UTC, leonardodiasb commented on script.js
> +  </div>
- [OPTIONAL] The 'Featured Speakers' section is a list of speakers, so probably wrapping the list with a `ul` tag and each speaker with the `li` tag would be better for semantics.

2022-10-19 20:26 UTC, merged

2023-05-04 11:50 UTC, jonathanmunamire commented on about.html
> +                <h2 class="greet2">POLYGLOT LANGUAGES SCHOOL <br>KIGALI (RWANDA)</h2>
Great, I will implement that

2023-05-04 11:50 UTC, jonathanmunamire commented on about.html
> +            <a class="logo" href="index.html"><img src="IMG/logo.jpg" height="50vh"></a>
Great, I will implement that

2023-05-04 11:50 UTC, jonathanmunamire commented on about.html
> +            <img src="IMG/logo.jpg">
Great, I will implement that

2023-05-04 11:51 UTC, jonathanmunamire commented on index.html
> +            <a class="logo" href="index.html"><img src="IMG/logo.jpg" height="50vh"></a>
Great, I will implement that

2023-05-04 11:51 UTC, jonathanmunamire commented on script.js
> +  <img src="${cards.teacherImage}">
Great, I will implement that

2023-05-04 11:51 UTC, jonathanmunamire commented on script.js
> +  </div>
Great, I will implement that

2023-05-04 11:53 UTC, jonathanmunamire commented
Thank you so much @leonardodiasb for your review, I appreciate it. I will certainly take your feedback into consideration and make the necessary changes to improve my code. :pray: